#!/bin/bash
set -x

mkdir -p /etc/rancher/rke2/

cat <<EOF > /etc/rancher/rke2/config.yaml
token: "${token}"
server: https://${lb_ip}:9345
EOF

if [ ! -z "${rke2_version}" ]; then
  export INSTALL_RKE2_VERSION="${rke2_version}"
fi

export INSTALL_RKE2_TYPE="agent"

curl -sfL https://get.rke2.io | sh -

systemctl enable rke2-agent
systemctl start rke2-agent
