#!/bin/bash
set -x

mkdir -p /etc/rancher/rke2/

cat << 'EOF' > /etc/profile.d/rancher.sh
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
export CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock
PATH="$PATH:/var/lib/rancher/rke2/bin"
source <(kubectl completion bash)
alias k=kubectl
complete -F __start_kubectl k
EOF

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export HOME=/root

cat <<EOF > /etc/rancher/rke2/config.yaml
token: "${token}"
tls-san:
  - ${lb_ip}
EOF

if [ "${count}" -gt "0" ]; then
  echo "server: https://${lb_ip}:9345" >> /etc/rancher/rke2/config.yaml
fi

if [ ! -z "${rke2_version}" ]; then
  export INSTALL_RKE2_VERSION="${rke2_version}"
fi

curl -sfL https://get.rke2.io | sh -

systemctl enable rke2-server
systemctl start rke2-server

if [ "${count}" -eq "0" ]; then

  # Install Helm
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # If user defines rancher prime helm repository, and chart version exists within it, use the prime repository;
  # otherwise fall back to rancher-latest repository
  repo=rancher-latest/rancher
  if [ -n "${rancher_chart_repo}" ]; then
    helm repo add rancher-prime ${rancher_chart_repo}
    helm repo update

    # Check if the specified rancher version exists in the rancher-prime repository
    # Rancher Prime >= 2.13.1 uses rancher-prime chart name, check for both possible names
    if helm search repo rancher-prime/rancher-prime --version ${rancher_version} --fail-on-no-result; then
      repo=rancher-prime/rancher-prime
    elif helm search repo rancher-prime/rancher --version ${rancher_version} --fail-on-no-result; then
      repo=rancher-prime/rancher
    fi
  fi

  helm repo add jetstack https://charts.jetstack.io
  helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
  helm repo update

  # wait for the rke2-ingress-nginx-controller to be ready
  while ! /var/lib/rancher/rke2/bin/kubectl -n kube-system rollout status ds/rke2-ingress-nginx-controller; do
    sleep 5
  done

  helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true

  # wait for the cert-manager-webhook to be ready
  while ! /var/lib/rancher/rke2/bin/kubectl -n cert-manager rollout status deploy/cert-manager-webhook; do
    sleep 5
  done

  helm install rancher $repo --namespace cattle-system --create-namespace --set hostname=${lb_ip}.nip.io --version ${rancher_version} --set bootstrapPassword="${admin_password}"
fi
