#!/bin/bash
set -x

# Create RKE2 config file
mkdir -p /etc/rancher/rke2/
cat <<EOF > /etc/rancher/rke2/config.yaml
token: "${token}"
server: https://${lb_ip}:9345
EOF

# Set RKE2 version if specified
if [ ! -z "${rke2_version}" ]; then
  export INSTALL_RKE2_VERSION="${rke2_version}"
fi

# Specify RKE2 installation type as agent
export INSTALL_RKE2_TYPE="agent"

# Install RKE2 agent
curl -sfL https://get.rke2.io | sh -

# Enable and start RKE2 agent service
systemctl enable rke2-agent
systemctl start rke2-agent
